import { existsSync, mkdirSync, writeFileSync, copyFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { VideoPlan } from './config.js';

export interface PackageYouTubeOptions {
  plan?: VideoPlan;
  videoPath?: string;
  metadataDir?: string;
  thumbnailPath?: string;
  outDir: string;
}

export function packageYouTube(options: PackageYouTubeOptions): {
  outDir: string;
  files: string[];
} {
  const files: string[] = [];

  if (!existsSync(options.outDir)) mkdirSync(options.outDir, { recursive: true });

  const shortsDir = join(options.outDir, 'shorts');
  if (!existsSync(shortsDir)) mkdirSync(shortsDir, { recursive: true });

  if (options.videoPath && existsSync(options.videoPath)) {
    copyFileSync(options.videoPath, join(options.outDir, 'final-video.mp4'));
    files.push('final-video.mp4');
  }

  if (options.thumbnailPath && existsSync(options.thumbnailPath)) {
    copyFileSync(options.thumbnailPath, join(options.outDir, 'thumbnail.png'));
    files.push('thumbnail.png');
  }

  if (options.metadataDir && existsSync(options.metadataDir)) {
    for (const f of readdirSync(options.metadataDir)) {
      const src = join(options.metadataDir, f);
      const dst = join(options.outDir, f);
      if (f.endsWith('.json') || f.endsWith('.txt') || f.endsWith('.md')) {
        copyFileSync(src, dst);
        files.push(f);
      }
    }
  }

  const readme = [
    '# YouTube Package',
    '',
    `Generated by VideoLane v0.1.0`,
    '',
    '## Files',
    '',
    ...files.map(f => `- ${f}`),
    '',
    '## Upload Steps',
    '',
    '1. Open YouTube Studio',
    '2. Upload `final-video.mp4`',
    '3. Copy title from `title-options.txt`',
    '4. Copy description from `description.txt`',
    '5. Upload `thumbnail.png`',
    '6. Add tags from `tags.txt`',
    '7. Pin comment from `pinned-comment.txt`',
    '8. Follow `upload-checklist.md`',
  ].join('\n');

  writeFileSync(join(options.outDir, 'README.md'), readme);
  files.push('README.md');

  return { outDir: options.outDir, files };
}
